import "./globals.css";
import type { Metadata } from "next";

import localFont from "next/font/local";

const showtimeFont = localFont({
  src: "./Showtime.ttf",
  variable: "--font-showtime",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={showtimeFont.variable}>{children}</body>
    </html>
  );
}
